config/routes.rb
Rails.application.routes.draw do


  default_url_options :host => "http://localhost:3000"

  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks" }

  resources :employees do
    collection { post :import }
  end

  #devise_for :employees

  get 'employees/export', as: 'employees_export'

  resources :pages, :positions, :history, :departments, :vacations, :employees

  root 'welcome#index'
end

app/models/position.rb
class Position < ApplicationRecord
  validates :sallary, {numericality: {greater_than: 0}}
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @positions = Position.all
  end

  def show
    @position = Position.find(params[:id])
  end

  def new
    @position = Position.new
  end

  def edit
    @position = Position.find(params[:id])
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to @position
    else
      render 'new'
    end

  end

  def update
    @position = Position.find(params[:id])

    if @position.update(position_params)
      redirect_to @position
    else
      render 'edit'
    end
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    redirect_to positions_path
  end

  private
  def position_params
    params.require(:position).permit(:name, :sallary, :vacations_days)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def position_for_select
    Position.all.collect { |p| [p.name, p.id] }
  end
end

app/views/positions/_form.html.erb
<%= form_with scope: :position, url: positions_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :sallary %><br>
    <%= form.text_field :sallary %>
  </p>
  <p>
    <%= form.label :vacations_days %><br>
    <%= form.text_field :vacations_days %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/positions/index.html.erb
<h1>Positions </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<% @positions.each do |position| %>
  <tr>
    <td><%= position.id %></td>
    <td><%= position.name %></td>
    <td><%= position.sallary %></td>
    <td><%= position.vacations_days %></td>

    <td><%= link_to '|Show', position_path(position) %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position_path(position), method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <hr>
<% end %>

app/views/positions/new.html.erb
<h1>Add new position </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<%= render 'form' %>

app/views/positions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>
<p>
  <strong>Sallary:</strong>
  <%= @position.sallary %>
</p>
<p>
  <strong>Vacations days:</strong>
  <%= @position.vacations_days %>
</p>
<tr>
  <td><%= link_to 'Edit', edit_position_path%></td>
  <td><%= link_to 'Destroy', position_path, method: :delete, data: { confirm: 'Are you sure?' }%>
</tr>
<%= link_to "View all positions", positions_path%>