config/routes.rb
Rails.application.routes.draw do


  default_url_options :host => "http://localhost:3000"

  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks" }

  resources :employees do
    collection { post :import }
  end

  #devise_for :employees

  get 'employees/export', as: 'employees_export'

  resources :pages, :positions, :history, :departments, :vacations, :employees

  root 'welcome#index'
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :employee
begin
  validate do
    self.errors[:date_start] << "must be a valid date" unless (DateTime.parse(self.start) rescue false)
  end
  validate do
    self.errors[:date_end] << "must be a valid date" unless (DateTime.parse(self.start) rescue false)
  end
end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  def index
      @vacations = Vacation.all
  end

  def show
    @vacation = Vacation.find(params[:id])
  end

  def new
    @vacation = Vacation.new
  end

  def edit
    @vacation = Vacation.find(params[:id])
  end

  def create
    @vacation = Vacation.new(vacation_params)
    if @vacation.save
      redirect_to @vacation
    else
      render 'new'
    end
  end

  def update
    @vacation = Vacation.find(params[:id])

    if @vacation.update(department_params)
      redirect_to @vacation
    else
      render 'edit'
    end
  end

  def destroy
    @vacation = Vacation.find(params[:id])
    @vacation.destroy

    redirect_to vacations_path
  end

  private
  def vacation_params
    params.require(:vacation).permit(:employee_id, :date_start, :date_end)
  end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.erb
<%= form_with scope: :vacation, url: vacations_path, local: true do |form| %>
  <p>
    <%= form.label :employee %><br>
    <%= form.collection_select(:employee_id, Employee.all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.label :date_start %><br>
    <%= form.text_field :date_start %>
  </p>
  <p>
    <%= form.label :date_end %><br>
    <%= form.text_field :date_end %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/vacations/edit.html.erb
<h1>Editing vacation</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/vacations/index.html.erb
<h1>Add new vacation </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<% @vacations.each do |vacation| %>
  <tr>
    <td><%= vacation.id %></td>
    <td><%= vacation.employee %></td>
    <td><%= vacation.date_start %></td>
    <td><%= vacation.date_end %></td>
    <td><%= link_to 'Show', vacation_path(vacation) %></td>
    <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
    <td><%= link_to 'Destroy', vacation_path(vacation), method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <hr>
<% end %>

app/views/vacations/new.html.erb
<h1>Add new vacation </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<%= render 'form' %>

app/views/vacations/show.html.erb
<p>
  <strong>Employee:</strong>
  <%= @vacation.employee %>
</p>
<p>
  <strong>Date start:</strong>
  <%= @vacation.date_start %>
</p>
<p>
  <strong>Date end:</strong>
  <%= @vacation.date_end %>
</p>
<tr>
  <td><%= link_to 'Edit', edit_vacation_path%></td>
  <td><%= link_to 'Destroy', vacations_path, method: :delete, data: { confirm: 'Are you sure?' }%>
</tr>
<%= link_to "View all vacations", vacations_path%>