config/routes.rb
Rails.application.routes.draw do


  default_url_options :host => "http://localhost:3000"

  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks" }

  resources :employees do
    collection { post :import }
  end

  #devise_for :employees

  get 'employees/export', as: 'employees_export'

  resources :pages, :positions, :history, :departments, :vacations, :employees

  root 'welcome#index'
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :employee
  belongs_to :position

  validate do
    self.errors[:date_start] << "must be a valid date" unless (DateTime.parse(self.start) rescue false)
  end

  validate do
    self.errors[:date_end] << "must be a valid date" unless (DateTime.parse(self.start) rescue false)
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @stories = History.all
  end

  def show
    @history = History.find(params[:id])
  end

  def new
    @history = History.new
  end

  def edit
    @history = History.find(params[:id])
  end

  def create
    @history = History.new(history_params)
    if @history.save
      redirect_to @history
    else
      render 'new'
    end
  end

  def update
    @history = History.find(params[:id])

    if @history.update(department_params)
      redirect_to @history
    else
      render 'edit'
    end
  end

  def destroy
    @history = History.find(params[:id])
    @history.destroy

    redirect_to historys_path
  end

  private
  def history_params
    params.require(:history).permit(:position_id, :date_start, :date_end, :employee_id )
  end
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/views/history/_form.html.erb
<%= form_with scope: :history, url: history_index_path, local: true do |form| %>
  <p>
    <%= form.label :employee %><br>
    <%= form.collection_select(:employee_id, Employee.all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.label :date_start %><br>
    <%= form.text_field :date_start %>
  </p>
  <p>
    <%= form.label :date_end %><br>
    <%= form.text_field :date_end %>
  </p>  <p>
  <%= form.label :position %><br>
  <%= form.collection_select(:employee_id, Position.all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/history/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/history/index.html.erb
<h1>History </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<% @stories.each do |history| %>
  <tr>
    <td><%= history.id %></td>
    <td><%= history.name %></td>
    <td><%= history.position %></td>
    <td><%= history.date_start %></td>
    <td><%= history.date_end %></td>
    <td><%= history.employee %></td>
    <td><%= link_to 'Show', history_path(history) %></td>
    <td><%= link_to 'Edit', edit_history_path(history) %></td>
    <td><%= link_to 'Destroy', history_path(history), method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <hr>
<% end %>

app/views/history/new.html.erb
<h1>Add new history </h1>
<h2>
  <%= link_to "Home", root_path %>
</h2>
<%= render 'form' %>

app/views/history/show.html.erb
<p>
  <strong>Date start:</strong>
  <%= @history.date_start %>
</p>
<p>
  <strong>Date end:</strong>
  <%= @history.date_end %>
</p>
<p>
  <strong>Position:</strong>
  <%= @history.position %>
</p>
<p>
  <strong>Employee:</strong>
  <%= @history.date_end %>
</p>
<tr>
  <td><%= link_to 'Edit', edit_history_path%></td>
  <td><%= link_to 'Destroy', history_path, method: :delete, data: { confirm: 'Are you sure?' }%>
</tr>
<%= link_to "View all departments", histories_path%>