config/routes.rb
Rails.application.routes.draw do


  default_url_options :host => "http://localhost:3000"

  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks" }

  resources :employees do
    collection { post :import }
  end

  #devise_for :employees

  get 'employees/export', as: 'employees_export'

  resources :pages, :positions, :history, :departments, :vacations, :employees

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Human Resouces</h1>
<h2>List:</h2>
<div>
  <ul>
    <li>
      <% if !employee_signed_in? %>
        <%= link_to "Sign up", new_employee_registration_path%>
        </li>
        <li>
          <%= link_to "Sign in", new_employee_session_path%>
        </li>
        <li>
          <%= link_to "Sign in with Facebook", employee_facebook_omniauth_authorize_path   %>
        </li>
      <% else %>
        <%= current_employee.email %>
        <%= link_to I18n.t('links.show'), employee_path(current_employee) %>
        <%= link_to 'Log out', destroy_employee_session_path, :method => :delete %>
      <% end %>
      <hr/>
      <li>
        <%= link_to "Add department", new_department_path%>
      </li>
      <li>
        <%= link_to "Show departments", departments_path %>
      </li>
      <li>
        <%= link_to "Add position", new_position_path %>
      </li>
      <li>
        <%= link_to "Show positions", positions_path %>
      </li>
      <li>
        <%= link_to "Add employee", new_employee_path%>
      </li>
      <li>
        <%= link_to "Show employees", employees_path %>
      </li>
      <li>
        <%= link_to "Add vacation", new_vacation_path %>
      </li>
      <li>
        <%= link_to "Show vacations", vacations_path %>
      </li>
      <li>
        <%= link_to "Add history", new_history_path %>
      </li>
      <li>
        <%= link_to "Show history", history_index_path %>
      </li>
      </ul>
</div>